## Welcome to my GitHub Pages
<!doc type html>
<html>
  <body dir = "rt\"
        <font size = "15"> <h2> <d> انگیزه نامه </b> </h2> <br>
  </font>
  <font size = "12"> طاهره صفری هستم متولد 1379 ترم چهار مهندسی کامپیوتر در دانشگاه پیام نور ملارد  <br>
  از ابتدا به این رشته علاقه داشتم به دلیل علاقه شدید به کامپیوتر و کد زنی و مچنین ساخت وب و نرم افزار ها <br>
  بیشترین انگیزه ام مربوط به مهاجرت میشه که از طریق این رشته خیلی راحت تر میتونم اقدام کنم و موقعیت شغلی و جایگاه خوبی پیدا کنم <br>
      </div>
    </body>
    </html>
