 طاهره صفری هستم 
 متولد 1379
 ترم چهار مهندسی کامپیوتر در دانشگاه پیام نور ملارد  
  از ابتدا به این رشته علاقه داشتم به دلیل علاقه شدید به کامپیوتر و کد زنی و مچنین ساخت وب و نرم افزار ها
  بیشترین انگیزه ام مربوط به مهاجرت میشه که از طریق این رشته خیلی راحت تر میتونم اقدام کنم و موقعیت شغلی و جایگاه خوبی پیدا کنم 
     
